name: generate

on:
  push:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v3
        env:
          GIT_TRACE: 0
          GIT_CURL_VERBOSE: 0

      - name: generate md.map
        run: |
            ls -lR
            ls -1 data/*.md > data/md.map
            mkdir -p html
            gh api --method POST \
                   -H "Accept: application/vnd.github+json" \
                   -H "X-GitHub-Api-Version: 2022-11-28" \
                   /markdown -f mode=gfm text="$(<data/2004-03-09.md)" >html/2004-03-09.html
            set +e  
            git add html/2004-03-09.html
            set -e
            git status
        env:
            GH_TOKEN: ${{ github.token }}

      - name: Update md.map inside repo
        run: |
            git add .
            set +e  # Grep succeeds with nonzero exit codes to show results.
            git status
            git status . | grep 'modified\|new file'
            if [ $? -eq 0 ]
            then
                set -e
                echo "git commit and push generated md.map file."
                git config --global user.name  "md.map"
                git config --global user.email "noone@nowhere.github.com"
                git commit -am "updated on - $(date)"
                git push
            else
                set -e
                echo "no changes since last run."
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
