name: generate

on:
  push:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0        
        env:
          GIT_TRACE: 0
          GIT_CURL_VERBOSE: 0
          
      - name: Convert Markdown to HTML
        run: |
          mkdir -p html
          for file in data/*.md; do
            filename=$(basename "$file" .md)
            html_file="html/${filename}.html"
            markdown=$(cat "$file")
            payload=$(jq -n --arg text "$markdown" --arg context "username/repo" '{text: $text, mode: "gfm", context: $context}')
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "$payload" \
                 https://api.github.com/markdown > "$html_file"
          done
      
      - name: generate md.map
        run: |
            echo step 1
            ls -lR
            echo step 2
            rm data/md.map
            echo step 3
            ls -1 data/*.md > data/md.map
            echo step 4
            mkdir -p html
            echo step 5
            echo "https://docs.github.com/en/get-started/writing-on-github" >html/2004-03-09.html
            echo step 6
            set +e  
            echo step 7
            git add html/2004-03-09.html
            echo step 8
            set -e
            echo step 9
            git status
            echo done
        env:
            GH_TOKEN: ${{ github.token }}

      - name: Update md.map inside repo
        run: |
            git add .
            set +e  # Grep succeeds with nonzero exit codes to show results.
            git status
            git status . | grep 'modified\|new file'
            if [ $? -eq 0 ]
            then
                set -e
                echo "git commit and push generated md.map file."
                git config --global user.name  "md.map"
                git config --global user.email "noone@nowhere.github.com"
                git commit -am "updated on - $(date)"
                git push
            else
                set -e
                echo "no changes since last run."
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
